site_name: 
site_url: 
site_description: 
theme:
  logo: 
  favicon: 
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  language: en
  features:
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 
      accent: 
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: 
      accent: 
      toggle:
        icon: material/weather-night
        name: Light Mode
  font:
    text: 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
plugins:
  - social
  - glightbox
  - search
copyright: 
extra:
  generator: false
repo_url: 
repo_name: 
edit_uri: edit/main/docs/

